# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3

# development:
#   adapter: postgresql
#   encoding: unicode
#   database: qna_development
#   hostname: 127.0.0.1
#   port: 5432
#   username: qna
#   password: qwerty

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: qna_test
#   hostname: 127.0.0.1
#   port: 5432
#   username: qna
#   password: qwerty
